spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  output:
    ansi:
      enabled: always

server:
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel.enabled: true